openapi: 3.1.0
info:
  version: 1.0.0
  title: Water tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of a water tracker app
tags:
  - name: User
    description: Operations with user data
  - name: Auth
    description: Authentication and authorisation operations
servers:
  - url: http://localhost:3000
  - url: https://browser-battalion-3-0-backend-kyxl.onrender.com
paths:
  /register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /{id}:
    get:
      $ref: ../swagger/paths/users/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
