openapi: 3.1.0
info:
  version: 1.0.0
  title: Water tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of a water tracker app
tags:
  - name: Auth
    description: Authentication and authorization operations
  - name: User
    description: Operations with user data
  - name: Water
    description: Documenting consumed water
servers:
  - url: https://browser-battalion-3-0-backend.onrender.com
  - url: https://browser-battalion-3-0-backend-kyxl.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /user/userById:
    get:
      $ref: '../swagger/paths/user/get.yaml'
  /user/update:
    patch:
      $ref: '../swagger/paths/user/patch.yaml'
  /user/avatar:
    patch:
      $ref: '../swagger/paths/user/avatar/patch.yaml'
  /user/waterRate:
    patch:
      $ref: '../swagger/paths/user/waterRate/patch.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/post.yaml'
  /water/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
  /water/today:
    get:
      $ref: '../swagger/paths/water/today/get.yaml'
  /water/month/{date}:
    get:
      $ref: '../swagger/paths/water/month/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
